### ISSUE TITLE
[Question] I need to make this echo out an if statement

### ISSUE THREAD

**Issue by joelmccauley** [imliam/laravel-blade-helper#1]
Can this do an if statement?

I want to be able to do:

@checkPermission($id, $permission_name)

So in view it would look like:
@checkPermission('11', 'add-user-to-site')
<p>You can add users to this site </p>
@endCheckPermission

I can't seem to find a way to get this to work?
I have it clear to the point where I can pull the correct information just can't get the if statement to echo out properly.

So $hasPermission = true;

return "if ($hasPermission):";

I love it other than this part :(

**Comment by imliam** [comment]
Hi, glad you like the package! I've just tagged a 1.1.0 release with support for generating custom "if" statement directives similarly to the core one in Blade. You can register it with `BladeHelper::if('directiveName', function() { ... });` and you can accept arguments through it like regular directives, and all you need to do is return a boolean value from it.

There's an example of how to use it in the readme; <https://github.com/imliam/laravel-blade-helper#custom-if-directive>

Let me know if this covers your use case if it doesn't feel free to reopen the issue.
