### ISSUE TITLE
Static Analysis

### ISSUE THREAD

**Issue by szepeviktor** [imliam/laravel-blade-helper#8]
Please consider running nunomaduro/larastan
Big benefit!

**Comment by imliam** [comment]
Feel free to make a PR, but I don't think this package would really benefit from it considering it's essentially 1 file and there's already tests ensuring it works as intended.

**Comment by szepeviktor** [comment]
Found no problems 🎉 

`vendor/bin/phpstan analyze -c vendor/nunomaduro/larastan/extension.neon -l max src/`
